-- MySQL Script generated by MySQL Workbench
-- Sun Jan 12 20:52:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema autognity_db_593408
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `autognity_db_593408` ;

-- -----------------------------------------------------
-- Schema autognity_db_593408
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autognity_db_593408` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `autognity_db_593408` ;

-- -----------------------------------------------------
-- Table `autognity_db_593408`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`users` ;

CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `violations` INT NOT NULL DEFAULT 0,
  `banned` TINYINT(1) NOT NULL DEFAULT 0,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expired` TIMESTAMP NULL,
  `public_key` VARCHAR(1023) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `usr_username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `address_UNIQUE` (`address` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `public_key_UNIQUE` (`public_key` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autognity_db_593408`.`robots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`robots` ;

CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`robots` (
  `robot_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `violations` INT NOT NULL DEFAULT 0,
  `banned` TINYINT(1) NOT NULL DEFAULT 0,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expired` TIMESTAMP NULL,
  `public_key` VARCHAR(1023) NULL,
  PRIMARY KEY (`robot_id`),
  UNIQUE INDEX `rob_username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `rob_user_id_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `public_key_UNIQUE` (`public_key` ASC) VISIBLE,
  CONSTRAINT `rob_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `autognity_db_593408`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autognity_db_593408`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`roles` ;

CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `parent` INT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `role_role_id_INDEX` (`parent` ASC) VISIBLE,
  CONSTRAINT `role_role_id`
    FOREIGN KEY (`parent`)
    REFERENCES `autognity_db_593408`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_parent`
    FOREIGN KEY (`parent`)
    REFERENCES `autognity_db_593408`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autognity_db_593408`.`robot_to_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`robot_to_role` ;

CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`robot_to_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `robot_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `rtr_robot_id_INDEX` (`robot_id` ASC) VISIBLE,
  INDEX `rtr_role_id_INDEX` (`role_id` ASC) VISIBLE,
  CONSTRAINT `rtr_robot_id`
    FOREIGN KEY (`robot_id`)
    REFERENCES `autognity_db_593408`.`robots` (`robot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rtr_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `autognity_db_593408`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autognity_db_593408`.`stations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`stations` ;

CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`stations` (
  `station_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `parent` INT NULL,
  PRIMARY KEY (`station_id`),
  INDEX `stn_station_id_INDEX` (`parent` ASC) VISIBLE,
  UNIQUE INDEX `stn_name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `stn_station_id`
    FOREIGN KEY (`parent`)
    REFERENCES `autognity_db_593408`.`stations` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `stn_parent`
    FOREIGN KEY (`parent`)
    REFERENCES `autognity_db_593408`.`stations` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autognity_db_593408`.`robot_to_station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`robot_to_station` ;

CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`robot_to_station` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `robot_id` INT NOT NULL,
  `station_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `rts_robot_id_INDEX` (`robot_id` ASC) INVISIBLE,
  INDEX `rts_station_id_INDEX` (`station_id` ASC) VISIBLE,
  CONSTRAINT `rts_robot_id`
    FOREIGN KEY (`robot_id`)
    REFERENCES `autognity_db_593408`.`robots` (`robot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rts_station_id`
    FOREIGN KEY (`station_id`)
    REFERENCES `autognity_db_593408`.`stations` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autognity_db_593408`.`bag_configs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`bag_configs` ;

CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`bag_configs` (
  `config_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `content` BLOB NOT NULL,
  PRIMARY KEY (`config_id`),
  INDEX `cfg_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `cfg_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `autognity_db_593408`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autognity_db_593408`.`bag_infos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`bag_infos` ;

CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`bag_infos` (
  `bag_id` INT NOT NULL AUTO_INCREMENT,
  `config_id` INT NOT NULL,
  `robot_id` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT '1970-01-01 01:00:01',
  `content` BLOB NOT NULL,
  `hash` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`bag_id`),
  INDEX `inf_config_id_INDEX` (`config_id` ASC) VISIBLE,
  INDEX `inf_robot_id_INDEX` (`robot_id` ASC) VISIBLE,
  CONSTRAINT `inf_config_id`
    FOREIGN KEY (`config_id`)
    REFERENCES `autognity_db_593408`.`bag_configs` (`config_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `inf_robot_id`
    FOREIGN KEY (`robot_id`)
    REFERENCES `autognity_db_593408`.`robots` (`robot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autognity_db_593408`.`topics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`topics` ;

CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`topics` (
  `topic_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`topic_id`),
  UNIQUE INDEX `tpc_name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autognity_db_593408`.`topic_to_station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`topic_to_station` ;

CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`topic_to_station` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `station_id` INT NOT NULL,
  `topic_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ctt_station_id_INDEX` (`station_id` ASC) INVISIBLE,
  INDEX `ctt_topic_id_INDEX` (`topic_id` ASC) VISIBLE,
  CONSTRAINT `stt_station_id`
    FOREIGN KEY (`station_id`)
    REFERENCES `autognity_db_593408`.`stations` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `stt_topic_id`
    FOREIGN KEY (`topic_id`)
    REFERENCES `autognity_db_593408`.`topics` (`topic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autognity_db_593408`.`robot_to_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`robot_to_config` ;

CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`robot_to_config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `robot_id` INT NOT NULL,
  `config_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `rtc_robot_id_INDEX` (`robot_id` ASC) VISIBLE,
  INDEX `rtc_config_id_INDEX` (`config_id` ASC) VISIBLE,
  CONSTRAINT `rtc_robot_id`
    FOREIGN KEY (`robot_id`)
    REFERENCES `autognity_db_593408`.`robots` (`robot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rtc_config_id`
    FOREIGN KEY (`config_id`)
    REFERENCES `autognity_db_593408`.`bag_configs` (`config_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autognity_db_593408`.`user_to_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`user_to_role` ;

CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`user_to_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `utr_role_id_INDEX` (`role_id` ASC) VISIBLE,
  INDEX `utr_user_id_INDEX` (`user_id` ASC) VISIBLE,
  CONSTRAINT `utr_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `autognity_db_593408`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `utr_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `autognity_db_593408`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autognity_db_593408`.`user_to_station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`user_to_station` ;

CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`user_to_station` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `station_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `uts_station_id_INDEX` (`station_id` ASC) VISIBLE,
  INDEX `uts_user_id_INDEX` (`user_id` ASC) VISIBLE,
  CONSTRAINT `uts_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `autognity_db_593408`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `uts_station_id`
    FOREIGN KEY (`station_id`)
    REFERENCES `autognity_db_593408`.`stations` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autognity_db_593408`.`bag_secrets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`bag_secrets` ;

CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`bag_secrets` (
  `secret_id` INT NOT NULL AUTO_INCREMENT,
  `bag_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `content` VARCHAR(1023) NOT NULL,
  PRIMARY KEY (`secret_id`),
  INDEX `sec_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `sec_bag_id_idx` (`bag_id` ASC) VISIBLE,
  CONSTRAINT `sec_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `autognity_db_593408`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sec_bag_id`
    FOREIGN KEY (`bag_id`)
    REFERENCES `autognity_db_593408`.`bag_infos` (`bag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autognity_db_593408`.`robot_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`robot_logs` ;

CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`robot_logs` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `robot_id` INT NOT NULL,
  `id` VARCHAR(8) NOT NULL,
  `content` BLOB NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  INDEX `rlog_robot_id_INDEX` (`robot_id` ASC) VISIBLE,
  UNIQUE INDEX `rlog_id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `rlog_robot_id`
    FOREIGN KEY (`robot_id`)
    REFERENCES `autognity_db_593408`.`robots` (`robot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autognity_db_593408`.`user_logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`user_logs` ;

CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`user_logs` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `id` VARCHAR(8) NOT NULL,
  `content` BLOB NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  INDEX `ulog_user_id_INDEX` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `ulog_id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `ulog_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `autognity_db_593408`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `autognity_db_593408` ;

-- -----------------------------------------------------
-- Placeholder table for view `autognity_db_593408`.`sub_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`sub_roles` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `autognity_db_593408`.`sub_stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`sub_stations` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `autognity_db_593408`.`station_topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`station_topics` (`station_id` INT, `station` INT, `topic` INT);

-- -----------------------------------------------------
-- Placeholder table for view `autognity_db_593408`.`robot_topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`robot_topics` (`robot_id` INT, `name` INT, `topic` INT);

-- -----------------------------------------------------
-- Placeholder table for view `autognity_db_593408`.`bags_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`bags_view` (`bag_id` INT, `config_id` INT, `robot_id` INT, `robot` INT, `hash` INT, `content` INT, `created` INT);

-- -----------------------------------------------------
-- Placeholder table for view `autognity_db_593408`.`super_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`super_roles` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `autognity_db_593408`.`robot_stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`robot_stations` (`robot_id` INT, `name` INT, `station_id` INT, `station` INT, `sup_id` INT, `sup` INT, `sub_id` INT, `sub` INT, `parent` INT);

-- -----------------------------------------------------
-- Placeholder table for view `autognity_db_593408`.`robot_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`robot_roles` (`robot_id` INT, `name` INT, `role_id` INT, `role` INT, `sup_id` INT, `sup` INT, `sub_id` INT, `sub` INT, `parent` INT);

-- -----------------------------------------------------
-- Placeholder table for view `autognity_db_593408`.`super_stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`super_stations` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `autognity_db_593408`.`logins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`logins` (`robot_id` INT, `user_id` INT, `name` INT, `username` INT, `password` INT, `violations` INT, `banned` INT, `created` INT, `expired` INT, `firstname` INT, `lastname` INT, `address` INT);

-- -----------------------------------------------------
-- Placeholder table for view `autognity_db_593408`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`user_roles` (`user_id` INT, `name` INT, `role_id` INT, `role` INT, `sup_id` INT, `sup` INT, `sub_id` INT, `sub` INT, `parent` INT);

-- -----------------------------------------------------
-- Placeholder table for view `autognity_db_593408`.`user_topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`user_topics` (`user_id` INT, `name` INT, `topic` INT);

-- -----------------------------------------------------
-- Placeholder table for view `autognity_db_593408`.`keys_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`keys_view` (`user_id` INT, `robot_id` INT, `name` INT, `public_key` INT, `created` INT, `expired` INT);

-- -----------------------------------------------------
-- Placeholder table for view `autognity_db_593408`.`log_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`log_roles` (`user_id` INT, `robot_id` INT, `name` INT, `role_id` INT, `role` INT, `sup_id` INT, `sup` INT, `sub_id` INT, `sub` INT, `parent` INT);

-- -----------------------------------------------------
-- Placeholder table for view `autognity_db_593408`.`log_stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`log_stations` (`user_id` INT, `robot_id` INT, `name` INT, `station_id` INT, `station` INT, `sup_id` INT, `sup` INT, `sub_id` INT, `sub` INT, `parent` INT);

-- -----------------------------------------------------
-- Placeholder table for view `autognity_db_593408`.`configs_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`configs_view` (`robot_id` INT, `user_id` INT, `config_id` INT, `user` INT, `robot` INT, `created` INT, `content` INT);

-- -----------------------------------------------------
-- Placeholder table for view `autognity_db_593408`.`secrets_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`secrets_view` (`secret_id` INT, `bag_id` INT, `user_id` INT, `name` INT, `content` INT);

-- -----------------------------------------------------
-- Placeholder table for view `autognity_db_593408`.`raws_view`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`raws_view` (`raw_id` INT, `bag_id` INT, `robot_id` INT, `content` INT);

-- -----------------------------------------------------
-- Placeholder table for view `autognity_db_593408`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autognity_db_593408`.`clients` (`robot_id` INT, `user_id` INT, `name` INT, `violations` INT, `banned` INT, `created` INT, `expired` INT, `firstname` INT, `lastname` INT, `address` INT);

-- -----------------------------------------------------
-- View `autognity_db_593408`.`super_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`super_roles`;
DROP VIEW IF EXISTS `autognity_db_593408`.`super_roles` ;
USE `autognity_db_593408`;
CREATE OR REPLACE VIEW `super_roles` AS (
	WITH RECURSIVE rec AS (
		SELECT role_id as r_id, role_id, name, parent FROM roles
        UNION ALL
        SELECT r_id, roles.role_id, roles.name, roles.parent FROM roles JOIN rec ON rec.parent = roles.role_id
	)
    SELECT r_id as role_id, roles.name as role, rec.role_id as sup_id, rec.name as sup, rec.parent as parent
    FROM rec LEFT JOIN roles ON r_id = roles.role_id WHERE r_id <> rec.role_id ORDER BY r_id
);

-- -----------------------------------------------------
-- View `autognity_db_593408`.`super_stations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`super_stations`;
DROP VIEW IF EXISTS `autognity_db_593408`.`super_stations` ;
USE `autognity_db_593408`;
CREATE OR REPLACE VIEW `super_stations` AS (
	WITH RECURSIVE rec AS (
		SELECT station_id as s_id, station_id, name, parent FROM stations
        UNION ALL
        SELECT s_id, stations.station_id, stations.name, stations.parent FROM stations JOIN rec ON rec.parent = stations.station_id
	)
    SELECT s_id as station_id, stations.name as station, rec.station_id as sup_id, rec.name as sup, rec.parent as parent
    FROM rec LEFT JOIN stations ON s_id = stations.station_id WHERE s_id <> rec.station_id ORDER BY s_id
);

-- -----------------------------------------------------
-- View `autognity_db_593408`.`sub_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`sub_roles`;
DROP VIEW IF EXISTS `autognity_db_593408`.`sub_roles` ;
USE `autognity_db_593408`;
CREATE OR REPLACE VIEW `sub_roles` AS (
	WITH RECURSIVE rec AS ( 
		SELECT role_id as r_id, role_id, name, parent FROM roles
		UNION ALL
		SELECT r_id, roles.role_id, roles.name, roles.parent FROM roles JOIN rec ON rec.role_id = roles.parent
	)
    SELECT r_id as role_id, roles.name as role, rec.role_id as sub_id, rec.name as sub, rec.parent as parent FROM rec
    LEFT JOIN roles ON r_id = roles.role_id WHERE r_id <> rec.role_id ORDER BY r_id
);

-- -----------------------------------------------------
-- View `autognity_db_593408`.`sub_stations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`sub_stations`;
DROP VIEW IF EXISTS `autognity_db_593408`.`sub_stations` ;
USE `autognity_db_593408`;
CREATE OR REPLACE VIEW `sub_stations` AS (
	WITH RECURSIVE rec AS ( 
		SELECT station_id as s_id, station_id, name, parent FROM stations
		UNION ALL
		SELECT s_id, stations.station_id, stations.name, stations.parent FROM stations JOIN rec ON rec.station_id = stations.parent
	)
    SELECT s_id as station_id, stations.name as station, rec.station_id as sub_id, rec.name as sub, rec.parent as parent FROM rec
    LEFT JOIN stations ON s_id = stations.station_id WHERE s_id <> rec.station_id ORDER BY s_id
);

-- -----------------------------------------------------
-- View `autognity_db_593408`.`station_topics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`station_topics`;
DROP VIEW IF EXISTS `autognity_db_593408`.`station_topics` ;
USE `autognity_db_593408`;
CREATE OR REPLACE VIEW `station_topics` AS
	SELECT station_id, stations.name as station, topics.name as topic FROM stations
    LEFT JOIN topic_to_station USING (station_id) LEFT JOIN topics USING (topic_id)
    ORDER BY station_id;

-- -----------------------------------------------------
-- View `autognity_db_593408`.`robot_topics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`robot_topics`;
DROP VIEW IF EXISTS `autognity_db_593408`.`robot_topics` ;
USE `autognity_db_593408`;
CREATE OR REPLACE VIEW `robot_topics` AS 
	SELECT robots.robot_id, robots.name, station_topics.topic FROM robots
    RIGHT JOIN robot_to_station USING (robot_id) LEFT JOIN station_topics USING (station_id)
    ORDER BY robots.robot_id;

-- -----------------------------------------------------
-- View `autognity_db_593408`.`bags_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`bags_view`;
DROP VIEW IF EXISTS `autognity_db_593408`.`bags_view` ;
USE `autognity_db_593408`;
CREATE OR REPLACE VIEW `bags_view` AS
	SELECT bag_infos.bag_id, bag_infos.config_id, bag_infos.robot_id, robots.name AS robot, bag_infos.hash, bag_infos.content, bag_infos.created
    FROM bag_infos LEFT JOIN robots USING (robot_id) LEFT JOIN bag_configs USING (config_id) ORDER BY bag_id;

-- -----------------------------------------------------
-- View `autognity_db_593408`.`robot_stations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`robot_stations`;
DROP VIEW IF EXISTS `autognity_db_593408`.`robot_stations` ;
USE `autognity_db_593408`;
CREATE OR REPLACE VIEW `robot_stations` AS
	SELECT robots.robot_id, robots.name, stations.station_id, stations.name as station, sup_id, sup, sub_id, sub, sub_stations.parent as parent
    FROM robots RIGHT JOIN robot_to_station USING (robot_id)
    LEFT JOIN stations USING (station_id)
    LEFT JOIN sub_stations ON (robot_to_station.station_id = sub_stations.station_id)
    LEFT JOIN super_stations ON (robot_to_station.station_id = super_stations.station_id)
    ORDER BY robots.robot_id;

-- -----------------------------------------------------
-- View `autognity_db_593408`.`robot_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`robot_roles`;
DROP VIEW IF EXISTS `autognity_db_593408`.`robot_roles` ;
USE `autognity_db_593408`;
CREATE OR REPLACE VIEW `robot_roles` AS
	SELECT robots.robot_id, robots.name, roles.role_id, roles.name as role, sup_id, sup, sub_id, sub, sub_roles.parent as parent
    FROM robots RIGHT JOIN robot_to_role USING (robot_id) LEFT JOIN roles ON (robot_to_role.role_id LIKE roles.role_id)
    LEFT JOIN sub_roles ON (robot_to_role.role_id LIKE sub_roles.role_id)
    LEFT JOIN super_roles ON (robot_to_role.role_id LIKE super_roles.role_id)
    ORDER BY robots.robot_id;

-- -----------------------------------------------------
-- View `autognity_db_593408`.`logins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`logins`;
DROP VIEW IF EXISTS `autognity_db_593408`.`logins` ;
USE `autognity_db_593408`;
CREATE OR REPLACE VIEW `logins` AS
	SELECT
		robot_id, user_id, robots.name, robots.username, robots.password, robots.violations, robots.banned,
		robots.created, robots.expired, firstname, lastname, address FROM robots LEFT JOIN users USING (user_id)
    UNION ALL
    SELECT
		null as robot_id, user_id, name, username, password, violations, banned,
		created, expired, firstname, lastname, address FROM users WHERE (user_id > 1);

-- -----------------------------------------------------
-- View `autognity_db_593408`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`user_roles`;
DROP VIEW IF EXISTS `autognity_db_593408`.`user_roles` ;
USE `autognity_db_593408`;
CREATE OR REPLACE VIEW `user_roles` AS
	SELECT users.user_id, users.name, roles.role_id, roles.name as role, sup_id, sup, sub_id, sub, sub_roles.parent as parent
    FROM users RIGHT JOIN user_to_role USING (user_id)
    LEFT JOIN roles ON (user_to_role.role_id LIKE roles.role_id)
    LEFT JOIN sub_roles ON (user_to_role.role_id LIKE sub_roles.role_id)
    LEFT JOIN super_roles ON (user_to_role.role_id LIKE super_roles.role_id)
    WHERE (user_id > 1)
    ORDER BY users.user_id;

-- -----------------------------------------------------
-- View `autognity_db_593408`.`user_topics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`user_topics`;
DROP VIEW IF EXISTS `autognity_db_593408`.`user_topics` ;
USE `autognity_db_593408`;
CREATE OR REPLACE VIEW `user_topics` AS 
	SELECT users.user_id, name, topic FROM users
    RIGHT JOIN user_to_station USING (user_id) LEFT JOIN station_topics USING (station_id)
    ORDER BY users.user_id;

-- -----------------------------------------------------
-- View `autognity_db_593408`.`keys_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`keys_view`;
DROP VIEW IF EXISTS `autognity_db_593408`.`keys_view` ;
USE `autognity_db_593408`;
CREATE OR REPLACE VIEW `keys_view` AS
	SELECT user_id, null AS robot_id, name, public_key, created, expired FROM users WHERE public_key IS NOT NULL
    UNION
    SELECT null AS user_id, robot_id, name, public_key, created, expired FROM robots WHERE public_key IS NOT NULL;

-- -----------------------------------------------------
-- View `autognity_db_593408`.`log_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`log_roles`;
DROP VIEW IF EXISTS `autognity_db_593408`.`log_roles` ;
USE `autognity_db_593408`;
CREATE  OR REPLACE VIEW `log_roles` AS
	SELECT user_id, null AS robot_id, name, role_id, role, sup_id, sup, sub_id, sub, parent FROM user_roles
    UNION ALL
    SELECT null AS user_id, robot_id, name, role_id, role, sup_id, sup, sub_id, sub, parent FROM robot_roles;

-- -----------------------------------------------------
-- View `autognity_db_593408`.`log_stations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`log_stations`;
DROP VIEW IF EXISTS `autognity_db_593408`.`log_stations` ;
USE `autognity_db_593408`;
CREATE  OR REPLACE VIEW `log_stations` AS
	SELECT user_id, null AS robot_id, name, station_id, station, sup_id, sup, sub_id, sub, parent FROM user_stations
    UNION ALL
    SELECT null AS user_id, robot_id, name, station_id, station, sup_id, sup, sub_id, sub, parent FROM robot_stations;

-- -----------------------------------------------------
-- View `autognity_db_593408`.`configs_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`configs_view`;
DROP VIEW IF EXISTS `autognity_db_593408`.`configs_view` ;
USE `autognity_db_593408`;
CREATE OR REPLACE VIEW `configs_view` AS
	SELECT robots.robot_id, users.user_id, bag_configs.config_id, users.name AS user, robots.name AS robot, bag_configs.created, bag_configs.content
    FROM bag_configs LEFT JOIN users USING (user_id)
    RIGHT JOIN robot_to_config USING (config_id) LEFT JOIN robots USING (robot_id) ORDER BY bag_configs.created DESC;

-- -----------------------------------------------------
-- View `autognity_db_593408`.`secrets_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`secrets_view`;
DROP VIEW IF EXISTS `autognity_db_593408`.`secrets_view` ;
USE `autognity_db_593408`;
CREATE OR REPLACE VIEW `secrets_view` AS
	SELECT bag_secrets.secret_id, bag_secrets.bag_id, bag_secrets.user_id, users.name, bag_secrets.content
    FROM bag_secrets LEFT JOIN users USING (user_id) ORDER BY bag_secrets.bag_id;

-- -----------------------------------------------------
-- View `autognity_db_593408`.`raws_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`raws_view`;
DROP VIEW IF EXISTS `autognity_db_593408`.`raws_view` ;
USE `autognity_db_593408`;
CREATE  OR REPLACE VIEW `raws_view` AS
	SELECT bag_raws.raw_id, bag_raws.bag_id, bag_infos.robot_id, bag_raws.content FROM bag_raws
    LEFT JOIN bag_infos USING (bag_id) ORDER BY bag_id;

-- -----------------------------------------------------
-- View `autognity_db_593408`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autognity_db_593408`.`clients`;
DROP VIEW IF EXISTS `autognity_db_593408`.`clients` ;
USE `autognity_db_593408`;
CREATE OR REPLACE VIEW `clients` AS
	SELECT
		robot_id, user_id, robots.name, robots.violations, robots.banned, robots.created, robots.expired,
		firstname, lastname, address FROM robots LEFT JOIN users USING (user_id)
    UNION ALL
    SELECT
		null as robot_id, user_id, name, violations, banned, created, expired, firstname, lastname, address FROM users WHERE (user_id > 1);
USE `autognity_db_593408`;

DELIMITER $$

USE `autognity_db_593408`$$
DROP TRIGGER IF EXISTS `autognity_db_593408`.`user_BEFORE_INSERT` $$
USE `autognity_db_593408`$$
CREATE DEFINER = CURRENT_USER TRIGGER `autognity_db_593408`.`user_BEFORE_INSERT` BEFORE INSERT ON `users` FOR EACH ROW
BEGIN
	IF NEW.expired IS NULL THEN
		SET NEW.expired = DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL 1 YEAR);
	END IF;
END$$


USE `autognity_db_593408`$$
DROP TRIGGER IF EXISTS `autognity_db_593408`.`robots_BEFORE_INSERT` $$
USE `autognity_db_593408`$$
CREATE DEFINER = CURRENT_USER TRIGGER `autognity_db_593408`.`robots_BEFORE_INSERT` BEFORE INSERT ON `robots` FOR EACH ROW
BEGIN
	IF NEW.expired IS NULL THEN
		SET NEW.expired = DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL 1 YEAR);
	END IF;
END$$


USE `autognity_db_593408`$$
DROP TRIGGER IF EXISTS `autognity_db_593408`.`roles_BEFORE_INSERT` $$
USE `autognity_db_593408`$$
CREATE DEFINER = CURRENT_USER TRIGGER `autognity_db_593408`.`roles_BEFORE_INSERT` BEFORE INSERT ON `roles` FOR EACH ROW
BEGIN
	IF NEW.parent LIKE 1 THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cannot associate the new role with the guest role';
	END IF;
END;$$


USE `autognity_db_593408`$$
DROP TRIGGER IF EXISTS `autognity_db_593408`.`stations_BEFORE_INSERT` $$
USE `autognity_db_593408`$$
CREATE DEFINER = CURRENT_USER TRIGGER `autognity_db_593408`.`stations_BEFORE_INSERT` BEFORE INSERT ON `stations` FOR EACH ROW
BEGIN
	IF NEW.parent LIKE 1 THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cannot associate the new station with the guests station';
	END IF;
END$$


USE `autognity_db_593408`$$
DROP TRIGGER IF EXISTS `autognity_db_593408`.`bag_infos_BEFORE_INSERT` $$
USE `autognity_db_593408`$$
CREATE DEFINER = CURRENT_USER TRIGGER `autognity_db_593408`.`bag_infos_BEFORE_INSERT` BEFORE INSERT ON `bag_infos` FOR EACH ROW
BEGIN
	IF NEW.hash IS NULL THEN
		SET NEW.hash = '';
	END IF;
END$$


DELIMITER ;
SET SQL_MODE = '';
DROP USER IF EXISTS admin_577341;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'admin_577341' IDENTIFIED BY '1FiA9HY2ITo6OGQu';

GRANT SELECT ON TABLE `autognity_db_593408`.`roles` TO 'admin_577341';
GRANT SELECT ON TABLE `autognity_db_593408`.`stations` TO 'admin_577341';
GRANT SELECT ON TABLE `autognity_db_593408`.`log_roles` TO 'admin_577341';
GRANT INSERT, DELETE, SELECT ON TABLE `autognity_db_593408`.`robots` TO 'admin_577341';
GRANT DELETE, INSERT, SELECT ON TABLE `autognity_db_593408`.`robot_to_config` TO 'admin_577341';
GRANT DELETE, INSERT, SELECT ON TABLE `autognity_db_593408`.`robot_to_role` TO 'admin_577341';
GRANT DELETE, INSERT, SELECT ON TABLE `autognity_db_593408`.`robot_to_station` TO 'admin_577341';
GRANT SELECT ON TABLE `autognity_db_593408`.`clients` TO 'admin_577341';
GRANT INSERT, UPDATE, SELECT ON TABLE `autognity_db_593408`.`bag_infos` TO 'admin_577341';
GRANT INSERT ON TABLE `autognity_db_593408`.`bag_secrets` TO 'admin_577341';
GRANT SELECT ON TABLE `autognity_db_593408`.`clients` TO 'admin_577341';
GRANT SELECT ON TABLE `autognity_db_593408`.`log_roles` TO 'admin_577341';
GRANT SELECT ON TABLE `autognity_db_593408`.`log_stations` TO 'admin_577341';
GRANT SELECT ON TABLE `autognity_db_593408`.`keys_view` TO 'admin_577341';
GRANT SELECT ON TABLE `autognity_db_593408`.`bags_view` TO 'admin_577341';
GRANT SELECT ON TABLE `autognity_db_593408`.`configs_view` TO 'admin_577341';
GRANT SELECT ON TABLE `autognity_db_593408`.`user_roles` TO 'admin_577341';
GRANT SELECT ON TABLE `autognity_db_593408`.`robot_roles` TO 'admin_577341';
GRANT SELECT ON TABLE `autognity_db_593408`.`robot_stations` TO 'admin_577341';
GRANT SELECT ON TABLE `autognity_db_593408`.`secrets_view` TO 'admin_577341';
GRANT SELECT ON TABLE `autognity_db_593408`.`raws_view` TO 'admin_577341';
GRANT UPDATE, SELECT ON TABLE `autognity_db_593408`.`robots` TO 'admin_577341';
GRANT UPDATE, SELECT ON TABLE `autognity_db_593408`.`users` TO 'admin_577341';
GRANT INSERT ON TABLE `autognity_db_593408`.`robot_to_config` TO 'admin_577341';
GRANT INSERT ON TABLE `autognity_db_593408`.`bag_configs` TO 'admin_577341';
GRANT UPDATE, SELECT ON TABLE `autognity_db_593408`.`users` TO 'admin_577341';
GRANT INSERT, DELETE, SELECT ON TABLE `autognity_db_593408`.`users` TO 'admin_577341';
GRANT SELECT ON TABLE `autognity_db_593408`.`roles` TO 'admin_577341';
GRANT SELECT ON TABLE `autognity_db_593408`.`stations` TO 'admin_577341';
GRANT DELETE, INSERT, SELECT ON TABLE `autognity_db_593408`.`user_to_role` TO 'admin_577341';
GRANT DELETE, INSERT, SELECT ON TABLE `autognity_db_593408`.`user_to_station` TO 'admin_577341';
GRANT SELECT ON TABLE `autognity_db_593408`.`clients` TO 'admin_577341';
SET SQL_MODE = '';
DROP USER IF EXISTS login_104869;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'login_104869' IDENTIFIED BY 'qudLenrbijxdj9ZI';

GRANT DELETE, UPDATE, SELECT ON TABLE `autognity_db_593408`.`users` TO 'login_104869';
GRANT INSERT ON TABLE `autognity_db_593408`.`user_logs` TO 'login_104869';
GRANT UPDATE, DELETE, SELECT ON TABLE `autognity_db_593408`.`robots` TO 'login_104869';
GRANT INSERT ON TABLE `autognity_db_593408`.`robot_logs` TO 'login_104869';
GRANT SELECT ON TABLE `autognity_db_593408`.`logins` TO 'login_104869';
GRANT SELECT ON TABLE `autognity_db_593408`.`log_stations` TO 'login_104869';
GRANT SELECT ON TABLE `autognity_db_593408`.`log_roles` TO 'login_104869';
SET SQL_MODE = '';
DROP USER IF EXISTS guest_591932;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'guest_591932' IDENTIFIED BY 'z27CcDNwR0Evjl60';

GRANT UPDATE, SELECT ON TABLE `autognity_db_593408`.`users` TO 'guest_591932';
GRANT INSERT, DELETE, SELECT ON TABLE `autognity_db_593408`.`users` TO 'guest_591932';
GRANT SELECT ON TABLE `autognity_db_593408`.`roles` TO 'guest_591932';
GRANT SELECT ON TABLE `autognity_db_593408`.`stations` TO 'guest_591932';
GRANT DELETE, INSERT, SELECT ON TABLE `autognity_db_593408`.`user_to_role` TO 'guest_591932';
GRANT DELETE, INSERT, SELECT ON TABLE `autognity_db_593408`.`user_to_station` TO 'guest_591932';
GRANT SELECT ON TABLE `autognity_db_593408`.`clients` TO 'guest_591932';
SET SQL_MODE = '';
DROP USER IF EXISTS base_130849;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'base_130849' IDENTIFIED BY '0Av9dD4USJDTqerS';

GRANT INSERT, DELETE, SELECT ON TABLE `autognity_db_593408`.`users` TO 'base_130849';
GRANT SELECT ON TABLE `autognity_db_593408`.`roles` TO 'base_130849';
GRANT SELECT ON TABLE `autognity_db_593408`.`stations` TO 'base_130849';
GRANT DELETE, INSERT, SELECT ON TABLE `autognity_db_593408`.`user_to_role` TO 'base_130849';
GRANT DELETE, INSERT, SELECT ON TABLE `autognity_db_593408`.`user_to_station` TO 'base_130849';
GRANT SELECT ON TABLE `autognity_db_593408`.`clients` TO 'base_130849';
SET SQL_MODE = '';
DROP USER IF EXISTS owner_913285;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'owner_913285' IDENTIFIED BY 'WAY946b8Y4LBpjiE';

GRANT SELECT ON TABLE `autognity_db_593408`.`logins` TO 'owner_913285';
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE `autognity_db_593408`.`bag_configs` TO 'owner_913285';
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE `autognity_db_593408`.`bag_infos` TO 'owner_913285';
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE `autognity_db_593408`.`robot_to_config` TO 'owner_913285';
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE `autognity_db_593408`.`robot_to_role` TO 'owner_913285';
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE `autognity_db_593408`.`robot_to_station` TO 'owner_913285';
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE `autognity_db_593408`.`robots` TO 'owner_913285';
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE `autognity_db_593408`.`roles` TO 'owner_913285';
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE `autognity_db_593408`.`stations` TO 'owner_913285';
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE `autognity_db_593408`.`topic_to_station` TO 'owner_913285';
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE `autognity_db_593408`.`topics` TO 'owner_913285';
GRANT UPDATE, SELECT, INSERT, DELETE ON TABLE `autognity_db_593408`.`user_to_role` TO 'owner_913285';
GRANT INSERT, UPDATE, DELETE, SELECT ON TABLE `autognity_db_593408`.`user_to_station` TO 'owner_913285';
GRANT INSERT, UPDATE, SELECT, DELETE ON TABLE `autognity_db_593408`.`users` TO 'owner_913285';
GRANT SELECT ON TABLE `autognity_db_593408`.`keys_view` TO 'owner_913285';
GRANT SELECT ON TABLE `autognity_db_593408`.`bags_view` TO 'owner_913285';
GRANT SELECT ON TABLE `autognity_db_593408`.`robot_roles` TO 'owner_913285';
GRANT SELECT ON TABLE `autognity_db_593408`.`robot_stations` TO 'owner_913285';
GRANT SELECT ON TABLE `autognity_db_593408`.`robot_topics` TO 'owner_913285';
GRANT SELECT ON TABLE `autognity_db_593408`.`station_topics` TO 'owner_913285';
GRANT SELECT ON TABLE `autognity_db_593408`.`sub_roles` TO 'owner_913285';
GRANT SELECT ON TABLE `autognity_db_593408`.`sub_stations` TO 'owner_913285';
GRANT SELECT ON TABLE `autognity_db_593408`.`super_roles` TO 'owner_913285';
GRANT SELECT ON TABLE `autognity_db_593408`.`user_roles` TO 'owner_913285';
GRANT SELECT ON TABLE `autognity_db_593408`.`user_topics` TO 'owner_913285';
GRANT UPDATE, SELECT, INSERT, DELETE ON TABLE `autognity_db_593408`.`bag_secrets` TO 'owner_913285';
GRANT UPDATE, SELECT, DELETE, INSERT ON TABLE `autognity_db_593408`.`robot_logs` TO 'owner_913285';
GRANT UPDATE, SELECT, INSERT, DELETE ON TABLE `autognity_db_593408`.`user_logs` TO 'owner_913285';
GRANT SELECT ON TABLE `autognity_db_593408`.`configs_view` TO 'owner_913285';
GRANT SELECT ON TABLE `autognity_db_593408`.`log_roles` TO 'owner_913285';
GRANT SELECT ON TABLE `autognity_db_593408`.`log_stations` TO 'owner_913285';
GRANT SELECT ON TABLE `autognity_db_593408`.`raws_view` TO 'owner_913285';
GRANT SELECT ON TABLE `autognity_db_593408`.`secrets_view` TO 'owner_913285';
GRANT SELECT ON TABLE `autognity_db_593408`.`super_stations` TO 'owner_913285';
SET SQL_MODE = '';
DROP USER IF EXISTS robot_980236;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'robot_980236' IDENTIFIED BY '5SYwHsqybEPabNzh';

GRANT SELECT ON TABLE `autognity_db_593408`.`clients` TO 'robot_980236';
GRANT SELECT ON TABLE `autognity_db_593408`.`log_roles` TO 'robot_980236';
GRANT SELECT ON TABLE `autognity_db_593408`.`log_stations` TO 'robot_980236';
GRANT SELECT ON TABLE `autognity_db_593408`.`keys_view` TO 'robot_980236';
GRANT SELECT ON TABLE `autognity_db_593408`.`bags_view` TO 'robot_980236';
GRANT SELECT ON TABLE `autognity_db_593408`.`configs_view` TO 'robot_980236';
GRANT SELECT ON TABLE `autognity_db_593408`.`user_roles` TO 'robot_980236';
GRANT INSERT, UPDATE, SELECT ON TABLE `autognity_db_593408`.`bag_infos` TO 'robot_980236';
GRANT INSERT ON TABLE `autognity_db_593408`.`bag_secrets` TO 'robot_980236';
GRANT UPDATE, SELECT ON TABLE `autognity_db_593408`.`users` TO 'robot_980236';
GRANT INSERT, DELETE, SELECT ON TABLE `autognity_db_593408`.`users` TO 'robot_980236';
GRANT SELECT ON TABLE `autognity_db_593408`.`roles` TO 'robot_980236';
GRANT SELECT ON TABLE `autognity_db_593408`.`stations` TO 'robot_980236';
GRANT DELETE, INSERT, SELECT ON TABLE `autognity_db_593408`.`user_to_role` TO 'robot_980236';
GRANT DELETE, INSERT, SELECT ON TABLE `autognity_db_593408`.`user_to_station` TO 'robot_980236';
GRANT SELECT ON TABLE `autognity_db_593408`.`clients` TO 'robot_980236';
SET SQL_MODE = '';
DROP USER IF EXISTS user_012958;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'user_012958' IDENTIFIED BY 'frzuhhmseSz1Degn';

GRANT SELECT ON TABLE `autognity_db_593408`.`robot_roles` TO 'user_012958';
GRANT SELECT ON TABLE `autognity_db_593408`.`robot_stations` TO 'user_012958';
GRANT SELECT ON TABLE `autognity_db_593408`.`secrets_view` TO 'user_012958';
GRANT SELECT ON TABLE `autognity_db_593408`.`raws_view` TO 'user_012958';
GRANT UPDATE, SELECT ON TABLE `autognity_db_593408`.`robots` TO 'user_012958';
GRANT UPDATE, SELECT ON TABLE `autognity_db_593408`.`users` TO 'user_012958';
GRANT INSERT ON TABLE `autognity_db_593408`.`robot_to_config` TO 'user_012958';
GRANT INSERT ON TABLE `autognity_db_593408`.`bag_configs` TO 'user_012958';
GRANT SELECT ON TABLE `autognity_db_593408`.`clients` TO 'user_012958';
GRANT SELECT ON TABLE `autognity_db_593408`.`log_roles` TO 'user_012958';
GRANT SELECT ON TABLE `autognity_db_593408`.`log_stations` TO 'user_012958';
GRANT SELECT ON TABLE `autognity_db_593408`.`keys_view` TO 'user_012958';
GRANT SELECT ON TABLE `autognity_db_593408`.`bags_view` TO 'user_012958';
GRANT SELECT ON TABLE `autognity_db_593408`.`configs_view` TO 'user_012958';
GRANT SELECT ON TABLE `autognity_db_593408`.`user_roles` TO 'user_012958';
GRANT INSERT, DELETE, SELECT ON TABLE `autognity_db_593408`.`users` TO 'user_012958';
GRANT SELECT ON TABLE `autognity_db_593408`.`roles` TO 'user_012958';
GRANT SELECT ON TABLE `autognity_db_593408`.`stations` TO 'user_012958';
GRANT DELETE, INSERT, SELECT ON TABLE `autognity_db_593408`.`user_to_role` TO 'user_012958';
GRANT DELETE, INSERT, SELECT ON TABLE `autognity_db_593408`.`user_to_station` TO 'user_012958';
GRANT SELECT ON TABLE `autognity_db_593408`.`clients` TO 'user_012958';
GRANT UPDATE, SELECT ON TABLE `autognity_db_593408`.`users` TO 'user_012958';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `autognity_db_593408`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `autognity_db_593408`;
INSERT INTO `autognity_db_593408`.`users` (`user_id`, `name`, `firstname`, `lastname`, `address`, `username`, `password`, `violations`, `banned`, `created`, `expired`, `public_key`) VALUES (DEFAULT, 'guest', '.', '.', '.', 'Lg==', 'Lg==', 0, 1, DEFAULT, NULL, NULL);
INSERT INTO `autognity_db_593408`.`users` (`user_id`, `name`, `firstname`, `lastname`, `address`, `username`, `password`, `violations`, `banned`, `created`, `expired`, `public_key`) VALUES (DEFAULT, 'admin', '.', '.', 'todo@address.it', '516AAB195BE009C4F6677C91D49D14E8225148F6D813D208980E82315EFABE39', 'Lg==', 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `autognity_db_593408`.`roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `autognity_db_593408`;
INSERT INTO `autognity_db_593408`.`roles` (`role_id`, `name`, `parent`) VALUES (DEFAULT, 'guest', 2);
INSERT INTO `autognity_db_593408`.`roles` (`role_id`, `name`, `parent`) VALUES (DEFAULT, 'admin', 0);
INSERT INTO `autognity_db_593408`.`roles` (`role_id`, `name`, `parent`) VALUES (DEFAULT, 'mod', 2);
INSERT INTO `autognity_db_593408`.`roles` (`role_id`, `name`, `parent`) VALUES (DEFAULT, 'user', 3);
INSERT INTO `autognity_db_593408`.`roles` (`role_id`, `name`, `parent`) VALUES (DEFAULT, 'robot', 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `autognity_db_593408`.`stations`
-- -----------------------------------------------------
START TRANSACTION;
USE `autognity_db_593408`;
INSERT INTO `autognity_db_593408`.`stations` (`station_id`, `name`, `parent`) VALUES (DEFAULT, 'guests', 2);
INSERT INTO `autognity_db_593408`.`stations` (`station_id`, `name`, `parent`) VALUES (DEFAULT, 'main', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `autognity_db_593408`.`bag_configs`
-- -----------------------------------------------------
START TRANSACTION;
USE `autognity_db_593408`;
INSERT INTO `autognity_db_593408`.`bag_configs` (`config_id`, `user_id`, `created`, `content`) VALUES (DEFAULT, 2, CURRENT_TIMESTAMP, 0x6533303D);

COMMIT;


-- -----------------------------------------------------
-- Data for table `autognity_db_593408`.`topics`
-- -----------------------------------------------------
START TRANSACTION;
USE `autognity_db_593408`;
INSERT INTO `autognity_db_593408`.`topics` (`topic_id`, `name`, `type`) VALUES (DEFAULT, 'rosout', 'core');
INSERT INTO `autognity_db_593408`.`topics` (`topic_id`, `name`, `type`) VALUES (DEFAULT, 'roslink', 'core');
INSERT INTO `autognity_db_593408`.`topics` (`topic_id`, `name`, `type`) VALUES (DEFAULT, 'cmd_vel', 'turtle');
INSERT INTO `autognity_db_593408`.`topics` (`topic_id`, `name`, `type`) VALUES (DEFAULT, 'tele_op', 'turtle');

COMMIT;


-- -----------------------------------------------------
-- Data for table `autognity_db_593408`.`topic_to_station`
-- -----------------------------------------------------
START TRANSACTION;
USE `autognity_db_593408`;
INSERT INTO `autognity_db_593408`.`topic_to_station` (`id`, `station_id`, `topic_id`) VALUES (DEFAULT, 1, 1);
INSERT INTO `autognity_db_593408`.`topic_to_station` (`id`, `station_id`, `topic_id`) VALUES (DEFAULT, 2, 1);
INSERT INTO `autognity_db_593408`.`topic_to_station` (`id`, `station_id`, `topic_id`) VALUES (DEFAULT, 3, 1);
INSERT INTO `autognity_db_593408`.`topic_to_station` (`id`, `station_id`, `topic_id`) VALUES (DEFAULT, 1, 3);
INSERT INTO `autognity_db_593408`.`topic_to_station` (`id`, `station_id`, `topic_id`) VALUES (DEFAULT, 3, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `autognity_db_593408`.`user_to_role`
-- -----------------------------------------------------
START TRANSACTION;
USE `autognity_db_593408`;
INSERT INTO `autognity_db_593408`.`user_to_role` (`id`, `user_id`, `role_id`) VALUES (DEFAULT, 1, 1);
INSERT INTO `autognity_db_593408`.`user_to_role` (`id`, `user_id`, `role_id`) VALUES (DEFAULT, 2, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `autognity_db_593408`.`user_to_station`
-- -----------------------------------------------------
START TRANSACTION;
USE `autognity_db_593408`;
INSERT INTO `autognity_db_593408`.`user_to_station` (`id`, `user_id`, `station_id`) VALUES (DEFAULT, 1, 1);
INSERT INTO `autognity_db_593408`.`user_to_station` (`id`, `user_id`, `station_id`) VALUES (DEFAULT, 2, 2);

COMMIT;

